version: "3.9"
services:
  db:
    container_name: DataBase
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: page-recognition
    volumes:
      - type: volume
        source: api-postgres-volume
        target: /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
  page-recognize:
    container_name: Page-Recognize
    build:
      context: ./pageRecognition
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  api-postgres-volume: